"""
training_data.py
----------------
only trainig data is here app.py will import it.
"""

CATEGORIES = [
    "Payment Issue",
    "Technical Problem",
    "Product Inquiry",
    "Refund Request",
    "Delivery Issue"
]

TRAINING_DATA = [
    # ── Payment Issue (60 samples) ──────────────────────────────
    ("payment declined", "Payment Issue"),
    ("credit card not working", "Payment Issue"),
    ("billing error on invoice", "Payment Issue"),
    ("double charged for subscription", "Payment Issue"),
    ("paypal transaction failed", "Payment Issue"),
    ("my card was charged twice", "Payment Issue"),
    ("unable to add payment method", "Payment Issue"),
    ("refund not showing in bank", "Payment Issue"),
    ("payment method rejected", "Payment Issue"),
    ("invoice amount is wrong", "Payment Issue"),
    ("automatic payment failed", "Payment Issue"),
    ("credit limit exceeded", "Payment Issue"),
    ("transaction declined by bank", "Payment Issue"),
    ("debit card not accepted", "Payment Issue"),
    ("payment gateway error", "Payment Issue"),
    ("stripe payment failed", "Payment Issue"),
    ("apple pay not working", "Payment Issue"),
    ("google pay declined", "Payment Issue"),
    ("cannot process payment", "Payment Issue"),
    ("billing cycle error", "Payment Issue"),
    ("wrong amount charged", "Payment Issue"),
    ("unauthorized charge on account", "Payment Issue"),
    ("bank rejected my transaction", "Payment Issue"),
    ("prepaid card not accepted", "Payment Issue"),
    ("payment timeout error", "Payment Issue"),
    ("card expired but still charged", "Payment Issue"),
    ("duplicate invoice sent", "Payment Issue"),
    ("currency conversion issue", "Payment Issue"),
    ("international payment blocked", "Payment Issue"),
    ("payment pending too long", "Payment Issue"),
    ("subscription renewal failed", "Payment Issue"),
    ("cannot update billing info", "Payment Issue"),
    ("old card still being charged", "Payment Issue"),
    ("promo code not applying discount", "Payment Issue"),
    ("tax amount incorrect on bill", "Payment Issue"),
    ("checkout page payment error", "Payment Issue"),
    ("installment plan not working", "Payment Issue"),
    ("bank transfer not received", "Payment Issue"),
    ("net banking transaction failed", "Payment Issue"),
    ("UPI payment declined", "Payment Issue"),
    ("wallet balance not deducted correctly", "Payment Issue"),
    ("EMI option not available", "Payment Issue"),
    ("payment receipt not received", "Payment Issue"),
    ("invoice not generated after payment", "Payment Issue"),
    ("card number not accepted", "Payment Issue"),
    ("CVV mismatch error", "Payment Issue"),
    ("billing address mismatch", "Payment Issue"),
    ("payment link expired", "Payment Issue"),
    ("QR code payment failed", "Payment Issue"),
    ("crypto payment not confirmed", "Payment Issue"),
    ("gift card balance not applied", "Payment Issue"),
    ("loyalty points not redeemed", "Payment Issue"),
    ("coupon not working at checkout", "Payment Issue"),
    ("subscription charge before due date", "Payment Issue"),
    ("account charged after cancellation", "Payment Issue"),
    ("extra charges on my bill", "Payment Issue"),
    ("transaction stuck in processing", "Payment Issue"),
    ("payment split not working", "Payment Issue"),
    ("unable to pay via mobile app", "Payment Issue"),
    ("card declined for international purchase", "Payment Issue"),
    ("payment confirmation not sent", "Payment Issue"),

    # ── Technical Problem (60 samples) ─────────────────────────
    ("app crashes on startup", "Technical Problem"),
    ("login page not loading", "Technical Problem"),
    ("error 500 when saving", "Technical Problem"),
    ("password reset link expired", "Technical Problem"),
    ("two-factor authentication fails", "Technical Problem"),
    ("site is down", "Technical Problem"),
    ("cannot connect to server", "Technical Problem"),
    ("white screen after update", "Technical Problem"),
    ("feature not working", "Technical Problem"),
    ("slow performance", "Technical Problem"),
    ("data not syncing", "Technical Problem"),
    ("browser compatibility issue", "Technical Problem"),
    ("mobile app freezing", "Technical Problem"),
    ("unable to upload file", "Technical Problem"),
    ("error 404 page not found", "Technical Problem"),
    ("database connection error", "Technical Problem"),
    ("SSL certificate error", "Technical Problem"),
    ("session timeout too fast", "Technical Problem"),
    ("cannot download file", "Technical Problem"),
    ("video not playing", "Technical Problem"),
    ("audio not working in app", "Technical Problem"),
    ("notifications not showing", "Technical Problem"),
    ("dark mode not working", "Technical Problem"),
    ("search function broken", "Technical Problem"),
    ("cannot save settings", "Technical Problem"),
    ("profile picture not uploading", "Technical Problem"),
    ("map not loading", "Technical Problem"),
    ("API returning wrong data", "Technical Problem"),
    ("export to PDF broken", "Technical Problem"),
    ("copy paste not working", "Technical Problem"),
    ("keyboard shortcuts not responding", "Technical Problem"),
    ("infinite loading spinner", "Technical Problem"),
    ("form submission error", "Technical Problem"),
    ("image not displaying", "Technical Problem"),
    ("link redirects to wrong page", "Technical Problem"),
    ("account locked after failed login", "Technical Problem"),
    ("email verification not working", "Technical Problem"),
    ("OAuth login failing", "Technical Problem"),
    ("single sign on error", "Technical Problem"),
    ("app not updating to latest version", "Technical Problem"),
    ("push notifications not received", "Technical Problem"),
    ("location services not working", "Technical Problem"),
    ("calendar sync failing", "Technical Problem"),
    ("contacts not importing", "Technical Problem"),
    ("dashboard widgets not loading", "Technical Problem"),
    ("graph not rendering", "Technical Problem"),
    ("print function broken", "Technical Problem"),
    ("drag and drop not working", "Technical Problem"),
    ("autocomplete not suggesting", "Technical Problem"),
    ("spell check disabled", "Technical Problem"),
    ("filter not applying correctly", "Technical Problem"),
    ("sort order broken", "Technical Problem"),
    ("pagination not working", "Technical Problem"),
    ("scroll not functioning", "Technical Problem"),
    ("zoom feature broken", "Technical Problem"),
    ("screen reader incompatibility", "Technical Problem"),
    ("high battery drain from app", "Technical Problem"),
    ("app using too much memory", "Technical Problem"),
    ("crash after iOS update", "Technical Problem"),
    ("crash after Android update", "Technical Problem"),
    ("cannot share content", "Technical Problem"),
    ("QR scanner not working", "Technical Problem"),
    ("barcode reader broken", "Technical Problem"),
    ("biometric login failing", "Technical Problem"),
    ("face ID not recognized", "Technical Problem"),
    ("fingerprint not accepted", "Technical Problem"),
    ("widget not displaying on home screen", "Technical Problem"),
    ("watchOS app crashing", "Technical Problem"),
    ("desktop app not opening", "Technical Problem"),
    ("Windows app compatibility issue", "Technical Problem"),
    ("Mac app not launching", "Technical Problem"),
    ("Linux version not working", "Technical Problem"),

    # ── Product Inquiry (60 samples) ────────────────────────────
    ("what are the dimensions", "Product Inquiry"),
    ("is this available in red", "Product Inquiry"),
    ("what is the warranty period", "Product Inquiry"),
    ("can you send me the user manual", "Product Inquiry"),
    ("do you have a larger size", "Product Inquiry"),
    ("price of model X123", "Product Inquiry"),
    ("ingredients list for this", "Product Inquiry"),
    ("battery life of this device", "Product Inquiry"),
    ("specifications", "Product Inquiry"),
    ("compare models", "Product Inquiry"),
    ("compatible accessories", "Product Inquiry"),
    ("where can I buy", "Product Inquiry"),
    ("is this product waterproof", "Product Inquiry"),
    ("what colors are available", "Product Inquiry"),
    ("does this come with a charger", "Product Inquiry"),
    ("what material is this made of", "Product Inquiry"),
    ("is there a kids version", "Product Inquiry"),
    ("maximum weight capacity", "Product Inquiry"),
    ("is this gluten free", "Product Inquiry"),
    ("allergen information", "Product Inquiry"),
    ("country of manufacture", "Product Inquiry"),
    ("is this eco friendly", "Product Inquiry"),
    ("does it support Bluetooth 5.0", "Product Inquiry"),
    ("what operating systems are supported", "Product Inquiry"),
    ("storage capacity options", "Product Inquiry"),
    ("RAM options available", "Product Inquiry"),
    ("processor speed", "Product Inquiry"),
    ("screen resolution", "Product Inquiry"),
    ("camera megapixels", "Product Inquiry"),
    ("zoom capability", "Product Inquiry"),
    ("does it have night mode", "Product Inquiry"),
    ("is there a trial version", "Product Inquiry"),
    ("free plan features", "Product Inquiry"),
    ("what is included in premium plan", "Product Inquiry"),
    ("number of users supported", "Product Inquiry"),
    ("cloud storage limit", "Product Inquiry"),
    ("offline mode available", "Product Inquiry"),
    ("does it work without internet", "Product Inquiry"),
    ("API access available", "Product Inquiry"),
    ("integration with third party apps", "Product Inquiry"),
    ("is there a desktop version", "Product Inquiry"),
    ("mobile app availability", "Product Inquiry"),
    ("what platforms does it support", "Product Inquiry"),
    ("age rating for this product", "Product Inquiry"),
    ("is this suitable for children", "Product Inquiry"),
    ("pet safe ingredients", "Product Inquiry"),
    ("vegan product options", "Product Inquiry"),
    ("organic certification", "Product Inquiry"),
    ("does it have a remote control", "Product Inquiry"),
    ("voice assistant compatible", "Product Inquiry"),
    ("smart home integration", "Product Inquiry"),
    ("energy consumption rating", "Product Inquiry"),
    ("noise level in decibels", "Product Inquiry"),
    ("heat resistance rating", "Product Inquiry"),
    ("IP rating for dust and water", "Product Inquiry"),
    ("length of power cable", "Product Inquiry"),
    ("voltage requirements", "Product Inquiry"),
    ("frequency compatibility", "Product Inquiry"),
    ("does it support 5G", "Product Inquiry"),
    ("SIM card type required", "Product Inquiry"),
    ("unlock status of the device", "Product Inquiry"),
    ("comes with warranty card", "Product Inquiry"),
    ("extended warranty available", "Product Inquiry"),
    ("spare parts availability", "Product Inquiry"),
    ("service center locations", "Product Inquiry"),
    ("product launch date", "Product Inquiry"),
    ("new version coming soon", "Product Inquiry"),
    ("discontinued product alternatives", "Product Inquiry"),
    ("bulk purchase pricing", "Product Inquiry"),
    ("wholesale options", "Product Inquiry"),
    ("sample available", "Product Inquiry"),

    # ── Refund Request (60 samples) ─────────────────────────────
    ("i want my money back", "Refund Request"),
    ("return this item", "Refund Request"),
    ("how to get a refund", "Refund Request"),
    ("i received a damaged product", "Refund Request"),
    ("cancel my order and refund", "Refund Request"),
    ("my return was rejected", "Refund Request"),
    ("when will i get my refund", "Refund Request"),
    ("warranty claim for defective item", "Refund Request"),
    ("wrong item received", "Refund Request"),
    ("not as described", "Refund Request"),
    ("refund not processed", "Refund Request"),
    ("return shipping label", "Refund Request"),
    ("product stopped working after a week", "Refund Request"),
    ("item missing from my order", "Refund Request"),
    ("counterfeit product received", "Refund Request"),
    ("size does not fit need to return", "Refund Request"),
    ("changed my mind want refund", "Refund Request"),
    ("accidental purchase want refund", "Refund Request"),
    ("duplicate order want one cancelled", "Refund Request"),
    ("subscription cancellation refund", "Refund Request"),
    ("annual plan cancelled mid year", "Refund Request"),
    ("unused portion refund", "Refund Request"),
    ("promotional item not received", "Refund Request"),
    ("gift order wrong want refund", "Refund Request"),
    ("defective item exchange", "Refund Request"),
    ("partial refund for missing parts", "Refund Request"),
    ("product expired before delivery", "Refund Request"),
    ("seal broken on arrival", "Refund Request"),
    ("package tampered with", "Refund Request"),
    ("product recalled want refund", "Refund Request"),
    ("wrong color received refund", "Refund Request"),
    ("item not compatible as advertised", "Refund Request"),
    ("refund to original payment method", "Refund Request"),
    ("store credit instead of refund", "Refund Request"),
    ("return policy question", "Refund Request"),
    ("return window expired exception", "Refund Request"),
    ("refund denied appeal", "Refund Request"),
    ("chargeback initiated", "Refund Request"),
    ("dispute transaction refund", "Refund Request"),
    ("partial order refund", "Refund Request"),
    ("overcharged want difference back", "Refund Request"),
    ("event cancelled need refund", "Refund Request"),
    ("flight cancelled refund", "Refund Request"),
    ("hotel booking refund", "Refund Request"),
    ("course not as described refund", "Refund Request"),
    ("digital product refund", "Refund Request"),
    ("in-app purchase refund", "Refund Request"),
    ("app subscription refund", "Refund Request"),
    ("game purchase refund", "Refund Request"),
    ("software license refund", "Refund Request"),
    ("download not working refund", "Refund Request"),
    ("service not delivered refund", "Refund Request"),
    ("freelancer did not complete work", "Refund Request"),
    ("contractor refund request", "Refund Request"),
    ("insurance claim reimbursement", "Refund Request"),
    ("medical expense refund", "Refund Request"),
    ("cashback not received", "Refund Request"),
    ("reward points refund", "Refund Request"),
    ("tax refund on purchase", "Refund Request"),
    ("price drop refund request", "Refund Request"),
    ("price match refund", "Refund Request"),

    # ── Delivery Issue (60 samples) ─────────────────────────────
    ("where is my package", "Delivery Issue"),
    ("tracking number not working", "Delivery Issue"),
    ("delayed shipment", "Delivery Issue"),
    ("item not delivered yet", "Delivery Issue"),
    ("delivery estimate is wrong", "Delivery Issue"),
    ("package marked delivered but not received", "Delivery Issue"),
    ("shipping address incorrect", "Delivery Issue"),
    ("carrier lost my order", "Delivery Issue"),
    ("missed delivery", "Delivery Issue"),
    ("package damaged in transit", "Delivery Issue"),
    ("no tracking update", "Delivery Issue"),
    ("customs clearance issue", "Delivery Issue"),
    ("order stuck at warehouse", "Delivery Issue"),
    ("shipped to wrong address", "Delivery Issue"),
    ("delivery rescheduled without notice", "Delivery Issue"),
    ("driver left without delivering", "Delivery Issue"),
    ("package left outside in rain", "Delivery Issue"),
    ("signature required but no one home", "Delivery Issue"),
    ("delivered to neighbor by mistake", "Delivery Issue"),
    ("wrong item in package", "Delivery Issue"),
    ("half of order missing", "Delivery Issue"),
    ("empty box delivered", "Delivery Issue"),
    ("tracking shows delivered but nothing arrived", "Delivery Issue"),
    ("package stolen after delivery", "Delivery Issue"),
    ("delivery attempted but gate was open", "Delivery Issue"),
    ("courier not ringing doorbell", "Delivery Issue"),
    ("express shipping not honored", "Delivery Issue"),
    ("standard shipping taking too long", "Delivery Issue"),
    ("international shipment delayed", "Delivery Issue"),
    ("shipment held at customs", "Delivery Issue"),
    ("import duties charged unexpectedly", "Delivery Issue"),
    ("wrong tracking number provided", "Delivery Issue"),
    ("two orders mixed up", "Delivery Issue"),
    ("fragile item not handled properly", "Delivery Issue"),
    ("liquid spilled inside package", "Delivery Issue"),
    ("electronics damaged in shipping", "Delivery Issue"),
    ("box arrived crushed", "Delivery Issue"),
    ("item broken inside packaging", "Delivery Issue"),
    ("insufficient packaging protection", "Delivery Issue"),
    ("delivery partner changed without notice", "Delivery Issue"),
    ("FedEx delivery issue", "Delivery Issue"),
    ("UPS tracking not updating", "Delivery Issue"),
    ("DHL shipment delayed", "Delivery Issue"),
    ("USPS package lost", "Delivery Issue"),
    ("Royal Mail delay", "Delivery Issue"),
    ("India Post tracking issue", "Delivery Issue"),
    ("Bluedart delivery failed", "Delivery Issue"),
    ("Delhivery not delivering", "Delivery Issue"),
    ("same day delivery not fulfilled", "Delivery Issue"),
    ("next day delivery missed", "Delivery Issue"),
    ("estimated delivery passed no update", "Delivery Issue"),
    ("order dispatched but not moving", "Delivery Issue"),
    ("shipment in transit for too long", "Delivery Issue"),
    ("return pickup not scheduled", "Delivery Issue"),
    ("return package not collected", "Delivery Issue"),
    ("pickup agent did not arrive", "Delivery Issue"),
    ("delivery window too wide", "Delivery Issue"),
    ("no option to choose delivery time", "Delivery Issue"),
    ("locker delivery not working", "Delivery Issue"),
    ("Amazon locker issue", "Delivery Issue"),
    ("package not fitting in mailbox", "Delivery Issue"),
    ("delivery instructions not followed", "Delivery Issue"),
    ("contactless delivery failed", "Delivery Issue"),
    ("cold chain item delivered warm", "Delivery Issue"),
    ("perishable item spoiled in transit", "Delivery Issue"),
    ("medical supply delivery delayed", "Delivery Issue"),
    ("urgent document delivery missed", "Delivery Issue"),
    ("overnight courier failed", "Delivery Issue"),
    ("bulk order partial delivery", "Delivery Issue"),
    ("wrong quantity delivered", "Delivery Issue"),
    ("items delivered without invoice", "Delivery Issue"),
    ("gift wrapping damaged", "Delivery Issue"),
    ("label printed incorrectly", "Delivery Issue"),
    ("barcode on package unreadable", "Delivery Issue"),
]